import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api } from "../api";

export default function Organization() {
  const { id } = useParams(); const [org, setOrg] = useState(null); const [projects, setProjects] = useState([]); const [members, setMembers] = useState([]); const [name, setName] = useState(""); const [memberId, setMemberId] = useState(""); const [role, setRole] = useState("MEMBER"); const [error, setError] = useState("");
  const load = () => Promise.all([api(`/organizations/${id}/`), api(`/projects/?organization=${id}`), api(`/memberships/?organization=${id}`)]).then(([o, p, m]) => { setOrg(o); setProjects(p.results); setMembers(m.results.filter((x) => String(x.organization) === id)); }).catch((e) => setError(e.message));
  useEffect(() => { load(); }, [id]);
  async function create(e) { e.preventDefault(); try { await api("/projects/", { method: "POST", body: { organization: id, name } }); setName(""); load(); } catch (e) { setError(e.message); } }
  async function addMember(e) { e.preventDefault(); try { await api("/memberships/", { method: "POST", body: { organization: id, user: memberId, role } }); setMemberId(""); load(); } catch (e) { setError(e.message); } }
  return <div className="card"><h1>{org?.name ?? "Organization"}</h1>{error && <p className="error">{error}</p>}<h2>Projects</h2><form className="task-form" onSubmit={create}><label>New project<input value={name} onChange={(e) => setName(e.target.value)} required /></label><button>Create project</button></form><ul className="task-list">{projects.map((p) => <li key={p.id}><Link to={`/projects/${p.id}`}>{p.name}</Link></li>)}</ul><h2>Members</h2><form className="task-form" onSubmit={addMember}><label>User ID<input type="number" value={memberId} onChange={(e) => setMemberId(e.target.value)} required /></label><label>Role<select value={role} onChange={(e) => setRole(e.target.value)}><option>ADMIN</option><option>MEMBER</option><option>VIEWER</option></select></label><button>Add member</button></form><ul>{members.map((m) => <li key={m.id}>{m.username} — <select value={m.role} onChange={(e) => api(`/memberships/${m.id}/`, { method: "PATCH", body: { role: e.target.value } }).then(load).catch((e) => setError(e.message))}><option>OWNER</option><option>ADMIN</option><option>MEMBER</option><option>VIEWER</option></select><button className="secondary" onClick={() => window.confirm(`Remove ${m.username}?`) && api(`/memberships/${m.id}/`, { method: "DELETE" }).then(load).catch((e) => setError(e.message))}>Remove</button></li>)}</ul></div>;
}
