import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api } from "../api";

export default function Organization() {
  const { id } = useParams();
  const [org, setOrg] = useState(null); const [projects, setProjects] = useState([]); const [members, setMembers] = useState([]); const [name, setName] = useState(""); const [query, setQuery] = useState(""); const [matches, setMatches] = useState([]); const [selected, setSelected] = useState(null); const [role, setRole] = useState("MEMBER"); const [error, setError] = useState("");
  const load = () => Promise.all([api(`/organizations/${id}/`), api(`/projects/?organization=${id}`), api(`/memberships/?organization=${id}`)]).then(([o, p, m]) => { setOrg(o); setProjects(p.results); setMembers(m.results); }).catch((e) => setError(e.message));
  useEffect(() => { load(); }, [id]);
  useEffect(() => { if (query.trim().length < 2) return setMatches([]); const timer = setTimeout(() => api(`/memberships/users/?q=${encodeURIComponent(query)}`).then((data) => setMatches(data.results)).catch((e) => setError(e.message)), 250); return () => clearTimeout(timer); }, [query]);
  async function create(e) { e.preventDefault(); try { await api("/projects/", { method: "POST", body: { organization: id, name } }); setName(""); load(); } catch (e) { setError(e.message); } }
  async function addMember(e) { e.preventDefault(); if (!selected) return; try { await api("/memberships/", { method: "POST", body: { organization: id, user: selected.id, role } }); setSelected(null); setQuery(""); setMatches([]); load(); } catch (e) { setError(e.message); } }
  return <div className="card"><header><h1>{org?.name ?? "Organization"}</h1><p className="muted">{projects.length} project{projects.length === 1 ? "" : "s"} · {members.length} member{members.length === 1 ? "" : "s"}</p></header>{error && <p className="error">{error}</p>}<section><div className="section-heading"><h2>Projects</h2><span className="muted">Open a board to work on tasks</span></div><form className="task-form" onSubmit={create}><label>New project<input value={name} onChange={(e) => setName(e.target.value)} required /></label><button>Create project</button></form>{projects.length === 0 ? <p className="muted empty-state">No projects yet.</p> : <ul className="resource-list">{projects.map((p) => <li key={p.id}><Link to={`/projects/${p.id}`}><span className="resource-icon project-icon">P</span><span><strong>{p.name}</strong><small>{p.status === "ACTIVE" ? "Active project" : "Archived project"}</small></span><span className="badge">{p.status}</span></Link></li>)}</ul>}</section><section><div className="section-heading"><h2>Members</h2><span className="muted">{members.length} total</span></div><details><summary>Add member</summary><form className="task-form" onSubmit={addMember}><label>Search username<input value={query} onChange={(e) => { setQuery(e.target.value); setSelected(null); }} placeholder="At least 2 characters" autoComplete="off" /></label>{!selected && matches.length > 0 && <ul className="task-list">{matches.map((user) => <li key={user.id}><button type="button" className="secondary" onClick={() => { setSelected(user); setMatches([]); }}>{user.username}</button></li>)}</ul>}{selected && <p>Adding <strong>{selected.username}</strong></p>}<label>Role<select value={role} onChange={(e) => setRole(e.target.value)}><option>ADMIN</option><option>MEMBER</option><option>VIEWER</option></select></label><button disabled={!selected}>Add selected member</button></form></details><ul>{members.map((m) => <li key={m.id}>{m.username} — <select value={m.role} onChange={(e) => api(`/memberships/${m.id}/`, { method: "PATCH", body: { role: e.target.value } }).then(load).catch((e) => setError(e.message))}><option>OWNER</option><option>ADMIN</option><option>MEMBER</option><option>VIEWER</option></select><button className="secondary" onClick={() => window.confirm(`Remove ${m.username}?`) && api(`/memberships/${m.id}/`, { method: "DELETE" }).then(load).catch((e) => setError(e.message))}>Remove</button></li>)}</ul></section></div>;
}
