import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { api } from "../api";

export default function Project() {
  const { id } = useParams();
  const [data, setData] = useState({ results: [] }); const [form, setForm] = useState({ title: "", description: "", priority: "MEDIUM", due_date: "" }); const [filters, setFilters] = useState({ status: "", priority: "", search: "" }); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = (url) => { setLoading(true); const query = new URLSearchParams({ project: id, ...filters }); Object.keys(filters).forEach((key) => !filters[key] && query.delete(key)); return api(url || `/tasks/?${query}`).then(setData).catch((e) => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, [id, filters.status, filters.priority, filters.search]);
  const set = (key, value) => setForm({ ...form, [key]: value });
  async function save(e) { e.preventDefault(); try { await api(editing ? `/tasks/${editing.id}/` : "/tasks/", { method: editing ? "PATCH" : "POST", body: editing ? form : { ...form, project: id } }); setEditing(null); setForm({ title: "", description: "", priority: "MEDIUM", due_date: "" }); load(); } catch (e) { setError(e.message); } }
  function edit(task) { setEditing(task); setForm({ title: task.title, description: task.description, priority: task.priority, due_date: task.due_date || "" }); }
  return <div className="card"><h1>Project tasks</h1><form className="task-form" onSubmit={save}><label>Title<input value={form.title} onChange={(e) => set("title", e.target.value)} required /></label><label>Description<textarea value={form.description} onChange={(e) => set("description", e.target.value)} /></label><label>Priority<select value={form.priority} onChange={(e) => set("priority", e.target.value)}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label><label>Due date<input type="date" value={form.due_date} onChange={(e) => set("due_date", e.target.value)} /></label><button>{editing ? "Save task" : "Add task"}</button>{editing && <button type="button" className="secondary" onClick={() => setEditing(null)}>Cancel</button>}</form><div className="row"><select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">All statuses</option><option value="TODO">To do</option><option value="IN_PROGRESS">In progress</option><option value="DONE">Done</option></select><select value={filters.priority} onChange={(e) => setFilters({ ...filters, priority: e.target.value })}><option value="">All priorities</option><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select><input placeholder="Search title" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} /></div>{error && <p className="error">{error}</p>}{loading ? <p className="muted">Loading tasks...</p> : data.results.length === 0 ? <p className="muted">No tasks to show.</p> : <ul className="task-list">{data.results.map((task) => <li key={task.id}><strong>{task.title}</strong><span className="badge">{task.status}</span><button className="secondary" onClick={() => api(`/tasks/${task.id}/`, { method: "PATCH", body: { status: task.status === "DONE" ? "TODO" : "DONE" } }).then(() => load()).catch((e) => setError(e.message))}>Change status</button><button className="secondary" onClick={() => edit(task)}>Edit</button><button className="secondary" onClick={() => window.confirm(`Delete ${task.title}?`) && api(`/tasks/${task.id}/`, { method: "DELETE" }).then(() => load()).catch((e) => setError(e.message))}>Delete</button></li>)}</ul>}<div className="row">{data.previous && <button onClick={() => load(data.previous.replace("/api", ""))}>Previous</button>}{data.next && <button onClick={() => load(data.next.replace("/api", ""))}>Next</button>}</div></div>;
}
